apiVersion: neuvector.com/v1
kind: NvClusterSecurityRule
metadata:
  name: ingress-nginx
spec:
  ingress:
  - action: allow
    applications:
    - HTTP
    - SSL
    name: nv.ingress-nginx-controller.ingress-nginx-ingress-1
    ports: any
    priority: 0
    selector:
      comment: ""
      name: Workload:ingress
      original_name: ""
  - action: deny
    applications:
    - any
    name: ingress-nginx-ingress-2
    ports: tcp/8443
    priority: 0
    selector:
      comment: ""
      criteria:
      - key: namespace
        op: '!='
        value: kube-system
      name: not-kube-system
      original_name: ""
  target:
    policymode: N/A
    selector:
      comment: The Ingress-Nginx service
      criteria:
      - key: service
        op: =
        value: ingress-nginx*
      grp_band_width: 0
      grp_sess_cur: 0
      grp_sess_rate: 0
      mon_metric: false
      name: ingress-nginx
      original_name: ""
