apiVersion: policy.kubewarden.io/v1
kind: PolicyManifest
metadata:
  name: ingress-snippet-blocker
  description: Blocks dangerous ingress-nginx annotations linked to CVE-2025-1974
  homepage: https://github.com/your-org/ingress-snippet-blocker
  source: https://github.com/your-org/ingress-snippet-blocker
  license: Apache-2.0
  version: v0.2.0
  scope: Cluster
rules:
  - apiGroups: ["networking.k8s.io"]
    apiVersions: ["v1"]
    resources: ["ingresses"]
    operations: ["CREATE", "UPDATE"]
executionMode: kubewarden-wapc
mutating: false
contextAware: false
