apiVersion: neuvector.com/v1
kind: NvClusterSecurityRule
metadata:
  name: ingress-nginx
spec:
  ingress:
  - action: deny
    applications:
    - any
    name: ingress-nginx-ingress-2
    ports: tcp/8443
    priority: 0
    selector:
      comment: ""
      criteria:
      - key: namespace
        op: '!='
        value: kube-system
      name: not-kube-system
      original_name: ""
  target:
    policymode: Protect
    selector:
      name: nv.rke2-ingress-nginx-controller.kube-system
      criteria:
      - key: service
        op: =
        value: rke2-ingress-nginx-controller.kube-system
      - key: domain
        op: =
        value: kube-system
