name: Release Policy to GHCR

on:
  push:
    tags:
      - "v*"

env:
  RUST_TARGET: wasm32-unknown-unknown
  REGISTRY: ghcr.io
  REPO: ${{ github.repository_owner }}/kw-policies/ingressnightmare-policy

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      K8S_OPENAPI_ENABLED_VERSION: "1.28"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install kwctl
        run: |
          curl -sSfL https://github.com/kubewarden/kwctl/releases/download/v1.23.0/kwctl-linux-x86_64.zip -o kwctl-linux-x86_64.zip
          unzip kwctl-linux-x86_64.zip
          chmod +x kwctl-linux-x86_64
          sudo mv kwctl-linux-x86_64 /usr/local/bin/kwctl

      - name: Add wasm target
        run: rustup target add ${{ env.RUST_TARGET }}

      - name: Build policy
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Annotate policy
        run: kwctl annotate -m metadata.yaml -u README.md -o ingressnightmare-policy.wasm target/${{ env.RUST_TARGET }}/release/ingressnightmare_policy.wasm

      - name: Push to GHCR
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          IMAGE="${{env.REGISTRY}}/${{ env.REPO }}:${VERSION}"
          kwctl push ingressnightmare-policy.wasm registry://$IMAGE
